### PR TITLE
rebuild for target platform hash

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This rebuild is needed to incorporate the target platform in the hash via https://github.com/conda/conda-build/pull/4065. Hopefully this will help with https://github.com/conda-forge/openjdk-feedstock/pull/93

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by ryanvolz** [comment]
The current `alsa-lib` (1.2.6.1) is fine, it's the older-but-still-pinned version (1.2.3) that has the hash collision. We'd need to rebuild that version (on a branch?) or get https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2319 merged to update the pin.

**Comment by ocefpaf** [comment]
> or get [conda-forge/conda-forge-pinning-feedstock#2319](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2319) merged to update the pin.

Just merged it. Sorry I missed it before. We can also rebuild the old one in a branch if you still need it.

**Comment by ryanvolz** [comment]
@izahn It probably still makes sense to rebuild 1.2.3. Do you want to update this PR to build that version (you can probably just set the number and pull the hash from an old commit) and then I can push it to a branch?

**Comment by izahn** [comment]
Oh nice, thanks everybody. I don't have a really strong opinion about making a `v1.2.3` branch or just waiting for the `1.2.6` migration, please do whatever you think is best.

**Comment by izahn** [comment]
> @izahn It probably still makes sense to rebuild 1.2.3. Do you want to update this PR to build that version (you can probably just set the number and pull the hash from an old commit) and then I can push it to a branch?

OK will do, thanks.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by ryanvolz** [comment]
Pushed to `1.2.3` branch.

**Pull request closed without merging**
